name = "mlbstats-mcp"
main = "src/index.js"
compatibility_date = "2025-01-06"

[build]
command = ""

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }